imperial-space/space-station14-public

Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
Добавляет значок коронера к карте агента
Из за [Тикета](https://discord.com/channels/1040938900039929917/1196147153383456908)
:cl:
- add: Синдикат вспомнил о существовании коронера, добавив его значок в карту агента.
=> Coroner icon into id card chameleon

Resources/Locale/ru-RU/imperial/ertcall/currencu.ftl
=> Фикс перевода

Content.Shared/Imperial/Playablecards/FoldableCardSystem.cs
Фиксит некоторые ошибки игральных карт, https://discord.com/channels/1040938900039929917/1205809868036907048
**Changelog**
:cl:
- tweak: Игральные Карты больше не являются спиритическими, а так же дистанционными, вы не можете больше переворачивать их на расстоянии или за призрака.
=> Playable cards fold fix

Content.Shared/Climbing/Systems/ClimbSystem.cs
Теперь вы не можете залезать на объекты, в которых вы находитесь
В ответ на тикет: https://discord.com/channels/1040938900039929917/1210916288902209548
=> Fix climbing on objects you are inside

Resources/Prototypes/Imperial/HephaestusStation/minuteman/head.yml
=> ймл файл в котором хочется менять слеши на бакслеш (Быстро фиксит минитменов)

Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml, Resources/Prototypes/Entities/Objects/Decoration/present.yml, Resources/Prototypes/Entities/Structures/Furniture/dresser.yml, Resources/Prototypes/Imperial/Presents/presents.yml
То что у нас не осуждается, но то, за что нас визарды могут запинать
=> Невозможность появления всякой фигни

Resources/Maps/Shuttles/ERTPresets/cliningERT.yml, Resources/Maps/Shuttles/ERTPresets/newERTBig.yml, Resources/Maps/Shuttles/ERTPresets/newERTSmall.yml, Resources/Prototypes/Imperial/ErtCall/ErtCallPresets.yml
New Big, Small and Janitor shuttles for callert command.
Добавлены шаттлы, сделанные маперами коммьюнити. Большой, Малый и Уборщиков.
=> New ERTPresets.

Resources/Prototypes/Imperial/Psychosis/reagents.yml, Resources/Prototypes/Reagents/toxins.yml
Дублирование PRa https://github.com/imperial-space/space-station14-public/pull/55 на ветку апстрима.
В этот раз не затрагиваю копьё, потому что оно уже занерфлено.
=> Pax and Betterpax Upstream

Resources/Locale/ru-RU/Imperial/TFG/GoldenLife/translate.ftl, Resources/Prototypes/Imperial/TFG/GoldenLife/delicacy.yml, Resources/Prototypes/Imperial/TFG/GoldenLife/presentable_things.yml
Быстрый фикс очень небольшой критической ошибки и ошибки в переводе.
=> A lit fast fix crash error and translate.

Resources/Prototypes/Imperial/TFG/GoldenLife/golden_ak.yml
=> Duplicate sprite golden_ak magazine upstream

Resources/Prototypes/Imperial/TFG/GoldenLife/golden_ak.yml
=> Fast fix golden Magazine.

Resources/Prototypes/Species/moth.yml
Дублирование фикса имён мотыльков. Дублирование на апстрим, естественно.
=> Moth names fix upstream duplicate

Resources/Prototypes/Imperial/Toughguys/funcrate.yml
Добавил новые игрушки в ящик игрушек игроков карго.
Когда делал игрушки - добавил их в спавнер на станции, но не в ящик.
Добавлены 3 строки ID в файл с ящиком для игрушек.
=> Фикс покупки новых игрушек

Resources/Maps/Shuttles/ERTPresets/predationERTMedium.yml, Resources/Prototypes/Imperial/ErtCall/ErtCallPresets.yml
Добавление шаттла ОБР средних размеров.
Шаттл имеет экипаж 10 человек, оборудован почти всем необходимым, кроме клонёрки, и рассчитан, как среднестатистический ответ ЦК на любой вызов о военной помощи.
Не рассчитан, как шаттл конца игры или шаттл восстановления станции.
=> New Medium ERT shuttle.

Resources/Maps/Shuttles/CentComShuttles/CentComDelegat.yml, Resources/Maps/Shuttles/CentComShuttles/CentComDiplomat.yml
Два шаттла для пЦК. 
Расположены по пути Resources/Maps/Shuttles/CentComShuttles
Дипломат - персональный, маленький.
Делегат - большой, с парой крупных отделов, личным кабинетом и комнатой отдыха.
Нужен для случаев, когда понадобится заспавнить пЦК. И буду использовать эти карты в дальнейших разработках.
=> CentCom Shuttles for Representative.

Resources/Prototypes/Imperial/TFG/GoldenLife/delicacy.yml
Один прототип был дублирован дважды в разных .yml И самое страшное - они имели одинаковый ID!
Пришлось это пофиксить.
=> PresentablePizzaBox : duplicate ID fix.

Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml, Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
удаляет её из рук грузчика, теперь её можно достать лишь в каргомате
**Changelog**
=> [Upstream] [Non-Modular] Респрайт карго: Обновление куртки

Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml, Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
дубликат [апстрим пра](https://github.com/imperial-space/space-station14-public/pull/114)
=> [Downstream] [Non-Modular] Респрайт карго: Обновление куртки

Resources/Prototypes/Imperial/TFG/GoldenLife/golden_ak.yml
Исправлен недочёт в пути к спрайту магазина. Теперь должен отображаться корректно.
=> Лёгкий фикс ошибки с магазином золотого АК

Resources/Locale/ru-RU/anomaly/anomaly.ftl, Resources/Locale/ru-RU/xenoarchaeology/artifact-crusher.ftl
=> фикс перевода у РнД

Resources/Locale/ru-RU/follower/follow-verb.ftl, Resources/Locale/ru-RU/portal/portal.ftl
=> Повторный фикс перевода

Resources/Locale/ru-RU/shuttles/timer.ftl
Основу перевел, другой текст на экране не вмещается
=> Перевод экрана

Resources/Prototypes/Imperial/GlassTables/GToilet_graph.yml, Resources/Prototypes/Imperial/GlassTables/imperial_furniture.yml, Resources/Prototypes/Imperial/GlassTables/imperial_furniture_prototypes.yml, Resources/Prototypes/Imperial/coffee_table/Graph.yml, Resources/Prototypes/Imperial/coffee_table/coffee_tables.yml, Resources/Prototypes/Imperial/coffee_table/constructions.yml, Resources/Prototypes/Recipes/Construction/Graphs/furniture/tables.yml
Исправлены Graph для золотого туалета, и столиков, добавленных нашим проектом (всех кофейных, уранового, бронеуранового и бронеплазменного). Теперь их опять можно строить через G меню.
=> Gold Toilet and Cofee Tables graphs fix. (upstream)

Resources/Locale/ru-RU/gases/gases.ftl, Resources/Locale/ru-RU/health-examinable/health-examinable-silicon.ftl, Resources/Locale/ru-RU/power/components/generator.ftl, Resources/Locale/ru-RU/salvage/salvage-magnet.ftl
=> Фикс перевода апстрима

Resources/Locale/ru-RU/Imperial/ertcall/DeathSquadturret.ftl, Resources/Locale/ru-RU/Imperial/ertcall/uplinkCatalog.ftl, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Imperial/ERT_SniperRifle/ert_sniper_projectile.yml, Resources/Prototypes/Imperial/ErtCall/DeathSquadturrent.yml, Resources/Prototypes/Imperial/ErtCall/ErtLoadouts.yml, Resources/Prototypes/Imperial/ErtCall/ErtPrototypes.yml, Resources/Prototypes/Imperial/ErtCall/uplink/ErtCallUplinkCatalog.yml, Resources/Prototypes/Imperial/Modsuits/Clothing/control.yml
Перенос моего баффа на апстрим.
Этого нет на апстриме.
Скопировано `cherry-pick`. Никаких дополнительных изменений.
=> Death squad buff for Upstream

Resources/Locale/ru-RU/machine-linking/transmitter_ports.ftl
Локализованы состояния стабилизатора аномалий.
Потому что должно быть на русском.
Внес дополнительные значения в наши ftl. Сугубо по локализации стабилизатора.
=> Локализация стабилизатора аномалий

Resources/Locale/ru-RU/xenoarchaeology/artifact-hints.ftl
Небольшой фикс локализации у артефактов
Прежний был кривой
Исправлена строчка в ftl
=> Фикс локаль

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Возвращает в шкаф ГВ платы для клонёрки.
С апстримом эти платы потерялись. Время вернуть один из способов возращения бедолаг в игру.
* Добавил в оба прототипа шкафа ГВ платы для клонёрки. Ко всем изменениям оставил коммент.
Работоспособность сборки протестирована на локалке, ошибок в консоли нет.
=> Клоны наносят ответный удар

Resources/Maps/Shuttles/CentComShuttles/CentComDelegat.yml
Исправлен шаттл CentComDelegat.
=> Fix Representative Shuttle

Resources/ServerInfo/Guidebook/Service/Chef.xml
Фиксит отображение странички шеф повара в внитриигровой help панели
Патамушта баг
Удалил строчку, которая пыталась подргузить несуществующий ентити ReagentContainerMilk
=> Фикс отображения странички шеф повара

Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml, Resources/Prototypes/Stacks/consumable_stacks.yml
Багфикс блинчиков с разными вкусами. Теперь, когда берёшь блинчик с черникой или шоколадом из стопки, он не превращается, неожиданно, в обычный блинчик.
=> Pancakes stacks fix

Resources/Prototypes/Imperial/Playablecards/cards.yml
Фикс коробки игральных карт, теперь её можно ложить в карманы и рюкзаки.
=> CardBin fix

Resources/ServerInfo/Guidebook/Cargo/Salvage.xml, Resources/ServerInfo/Guidebook/Engineering/AME.xml, Resources/ServerInfo/Guidebook/Science/Technologies.xml, Resources/ServerInfo/Guidebook/Service/Janitorial.xml
Фиксит Parse Error страничек внутриигровой помощи
Потому что баг
Были удалены ссылки на несуществующие прототипы или ссылка была изменена на подобный предмет
=> Фикс страничек внутриигровой помощи

Content.Server/Anomaly/AnomalySynchronizerSystem.cs, Resources/Locale/ru-RU/anomaly/anomaly.ftl
"Исправлено" описание одной кнопки в синхронизаторе аномалий.
=> Фикс описания кнопки.

Content.Server/Chemistry/EntitySystems/SolutionInjectOnCollideSystem.cs
Исправлен баг со стрелами. Теперь они вводят реагенты, только если на человеке нет скафандра со шлемом или же ЭП в скафандре открыт.
=> Багфикс стрел

Content.Server/Electrocution/ElectrocutionSystem.cs, Content.Shared/Prying/Systems/PryingSystem.cs, Content.Shared/Prying/events/PryingEvent.cs
Исправлен баг с возможностью вскрыть наэлектризованную дверь через ПКМ играя на зомби
=> Багфикс открытия дверей через ПКМ

Content.Server/Electrocution/ElectrocutionSystem.cs, Content.Shared/Prying/Systems/PryingSystem.cs, Content.Shared/Prying/events/PryingEvent.cs
Reverts imperial-space/space-station14-public#289
=> Revert "Багфикс открытия дверей через ПКМ"

Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml
Почему то для получения свинца подходит только бронированная сталь (ее можно получить только на некоторых картах и то эта вещь сугубо из ТГМС), а не обычная (Как было до апстрима). Из-за этого невозможно сварить ликоксид, блюспейс жидкость и тазинид.
Я также увеличил количество железа и углерода в стали, чтобы химики не смоги за несколько секунд сварить ликоксид на весь отдел СБ.
=> Возвращение в сталь свинца

Resources/Prototypes/Imperial/Spider_Queen/Spider_Queen.yml
Добавляет:
1. Добавляет анимацию паукам. 
2. Снижен урон от разгермы в два раза.
3. Пауки больше не светятся.
4. Королева пауков может командовать своим ульем через свою связь. (Создан отдельный radioChannel на :у)
=> Фикс пауков

Resources/Prototypes/Imperial/CompactDefib/compactdefib.yml
Исправлен баг с возможностью извлечения батареи компактного дефибриллятора
=> Багфикс компактного дефибриллятора

Content.Server/Ghost/Roles/GhostRoleSystem.cs, Content.Server/Tools/ToolSystem.Welder.cs, Resources/Changelog/Changelog.yml, Resources/Prototypes/Catalog/Fills/Items/belt.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/security.yml, Resources/Prototypes/Research/arsenal.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml, Resources/Prototypes/Roles/Jobs/Security/security_officer.yml, Resources/Prototypes/Roles/Jobs/Security/warden.yml
=> upstream 27-03-24

Content.Shared/Item/SharedItemSystem.cs
Исправлен баг с возможностью дюпа корпуса РИГ-а
Проблема крылась в системе предметом. В ней добавлялось действие через ПКМ, которое моментально переносило предмет без каких либо проверок в руки игроку. Отсюда и странное поведение с возможностью "оторвать" голову или корпус у какого либо скафандра.
=> Багфикс РИГ-ов

Content.Server/Bed/Cryostorage/CryostorageSystem.cs
Исправлен баг, связанный с возможностью вытащить шлем от скафандра и корпус Р.И.Г-а с человека в криохранилище
=> Багфикс криохранилища

Resources/Locale/ru-RU/Imperial/Spider_Queen/spider.ftl, Resources/Prototypes/Imperial/Spider_Queen/Spider_Queen.yml
Обновление пауков
- Рация пауков теперь работает.
- Исправлена ошибка, связанная с ходьбой.
- Пауки могут разговаривать.
- Кристалл заменён на осколок.
- earliestStart 30 -> earliestStart 15
- ХП паутины королевы увеличено.
- Другие фиксы.
=> Обновление пауков

Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/starterGearIAA.yml, Resources/Prototypes/Entities/Objects/Devices/IAA/pda.yml, Resources/Prototypes/Imperial/IAA.yml, Resources/Prototypes/Imperial/seniorOfficer/seniorofficerclothing.yml, Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml, Resources/Prototypes/Roles/Jobs/Wildcards/reporter.yml
Чемодан АВД пофикшен и изменен. В нем лежит ручка и папка, ручка цк теперь в КПК, печать теперь в рюкзаке.
РПС СО Теперь имеет размер как у БМ, которого и должна была быть, в ней теперь есть газовая граната, как в обычном поясе. Выдан свисток. Теперь у СО появляется доступ в оружейную и к детективу на лоупопе.
Репортеру выдан штатный микрофон и клипборд.
=> Изменения и фикс стартового снаряжения

Resources/Prototypes/Imperial/ArcaneStation/Spawners/ArcaneSpawners.yml
Эта ПРка меняет систему распределения ролей Arcane Station, что бы люди имели равные шансы на занятие роли.
=> Arcane RoleSpawners Change

Resources/Prototypes/Imperial/DeadSector/outer_clothing.yml, Resources/Prototypes/Imperial/DeadSector/weapons/weapons/launcher.yml, Resources/Prototypes/Imperial/DeadSector/weapons/weapons/sniper.yml
Удалён собственный код C#, отвечающий за механику зарядки экзоскелетов. Багфикс спрайтов. Мелкое изменение характеристики предмета
=> Dead sector

Content.Server/Imperial/ElectroMouse/ElectroMouseSystem.cs, Content.Shared/Imperial/ElectroMouse/Components/ElectroMouseComponent.cs
зафиксил уход энергии в минус. был связан с тем, что при покупке из магазина в компоненте энергия не уменьшалась, поэтому он думал, что хватает
=> Фикс шокомыши

Resources/Prototypes/Recipes/Construction/utilities.yml, Resources/Prototypes/Recipes/Crafting/Graphs/bots/honkbot.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/firebomb.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/flowercrown.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/flowerwreath.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/hairflower.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/improvised_shotgun.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/improvised_shotgun_shell.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/makeshiftstunprod.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/pipebomb.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/pneumatic_cannon.yml, Resources/Prototypes/Recipes/Crafting/Graphs/improvised/potato.yml, Resources/Prototypes/Recipes/Crafting/Graphs/strawhat.yml, Resources/Prototypes/Recipes/Crafting/Graphs/toys.yml, Resources/Prototypes/Recipes/Crafting/potato.yml, Resources/Prototypes/Stacks/power_stacks.yml
Правки в переводе/перевод недоделанного в прошлом ПРе
=> Фикс перевода меню строительства
