imperial-space/space-station14-public

- Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
- Resources/Prototypes/Imperial/Psychosis/reagents.yml
- Resources/Prototypes/Reagents/toxins.yml
О работе:
Добавляет паксу и его улучшенной версии минимальное требование по количеству для активации способности "Пацифизм".
Яд с наконечников копий при броске не может проникнуть в тело, если в слоте внешней одежды (скафандра или бронижелета) есть что-нибудь. Не затрагивает обычные удары в ближнем бою.
Зачем?:
По многочисленным просьбам. И что бы прекратить длиннющее обсуждение, из-за которого у меня начала болеть голова.
Детали:
Если вколоть сразу 5 ед. пакса, эффект "Пафицизм" подействует где-то на 1 секунду, после чего спадёт. Если действующего вещества будет больше 5 ед. (например, 7 или 10), эффект пацифизма будет действовать всё это время. Если постоянно вкалывать по 1 ед. вещества, когда его меньше 5 ед, то не произойдёт ничего.
Так что игрокам на дедах всё ещё стоит опасаться …
> A bit Pax nerf

- Resources/Locale/ru-RU/Imperial/BundleAKMS/duffelbag.ftl
- Resources/Locale/ru-RU/Imperial/BundleAKMS/uplink-catalog.ftl
- Resources/Prototypes/Imperial/BundleAKMS/duffelbag.yml
- Resources/Prototypes/Imperial/BundleAKMS/uplink_catalog.yml
Добавляет КРУТЕЙШИЙ!!! набор АКМС в аплинк ядерных оперативников, стоимость 23 ТК, в наборе имеется 3 запасных магазина на АКМС
Ядерным оперативным специалистам требуется оружие для дальних дистанций, исключающее возможность использования "Христова" из-за его низкой скорости стрельбы. Почему бы не предоставить им подходящее оружие для эффективного выполнения поставленных задач?
> Набор с АКМС в аплинке ядерных оперативников

- Resources/Prototypes/Species/moth.yml
Изменён путь для генератора имён моли. Теперь никаких имён, написанных на латинице.
> Fix Moth names

- Resources/Locale/ru-RU/Imperial/Toughguys/Other.ftl
- Resources/Prototypes/Imperial/TFG/Representative/ShuttleStuff.yml
- Resources/Prototypes/Imperial/Toughguys/plushie_EasterEgg.yml
- Resources/Prototypes/Imperial/Toughguys/plushie_prototypes.yml
Исправлен id для "Армянского Счастья". ArmenianStuff снова ссылается на "entity", а не "reagent".
Исправлены все id в ShuttleBooze.
----
Настроена противотапочковая система для защиты от Миртона. Колени прикрыты дополнительным слоем защиты.
> Fix Armenian Stuff 's id.

- Resources/Maps/Shuttles/ERTPresets/cliningERT.yml
- Resources/Maps/Shuttles/ERTPresets/predationCBURN.yml
- Resources/Maps/Shuttles/ERTPresets/predationERTBig.yml
- Resources/Maps/Shuttles/ERTPresets/predationERTSmall.yml
Всем новым ERT шаттлам добавлен компонент ShuttleName.
Чу-у-у-уть чуть доработаны шаттлы - на них добавленно больше ЛКП, что бы они меньше времени были полностью без света.
Потому что так надо.
> ShuttleName component for new ERT shuttles

- Content.Server/Imperial/ErtCall/ErtCallCommand.cs
- Resources/Prototypes/Imperial/ErtCall/ErtCallPresets.yml
Добавления сортировки в комманду callert. Переименование пресетов для того, что бы они более аккуратно смотрелись в списке.
Всё для эстетического комфорта Рубика.
------
Было:
Стало:
> Sorting system for callERT command.

- Resources/Prototypes/Imperial/Juristic department/Juristic deparment.yml
- Resources/Prototypes/Roles/Jobs/departments.yml
Юрист выписан из юридического департамента и возвращен в сервис.
Слишком много разногласий у игроков, вики, всех подряд. Юрист теперь выполняет роль обычного консультанта по юридическим вопросам. 
Выписал юриста из `Juristic deratment` в своем прототипе. Убрал комментирование у прошлого юриста.
> Юрист снова в сервисном отделе

- Resources/Locale/ru-RU/Imperial/ertcall/DeathSquadturret.ftl
- Resources/Locale/ru-RU/imperial/ertcall/uplinkCatalog.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Imperial/ERT_SniperRifle/ert_sniper_projectile.yml
- Resources/Prototypes/Imperial/ErtCall/DeathSquadturrent.yml
- Resources/Prototypes/Imperial/ErtCall/ErtLoadouts.yml
- Resources/Prototypes/Imperial/ErtCall/ErtPrototypes.yml
- Resources/Prototypes/Imperial/ErtCall/uplink/ErtCallUplinkCatalog.yml
- Resources/Prototypes/Imperial/Modsuits/Clothing/control.yml
Проведен небольшой ребаланс эскадрона смерти и его снаряжения, чтобы им было легче противостоять мерзким врагам корпорации!
В связи с недавним добавлением RCU эскадрон смерти слегка потерял позиции в вооружении по сравнению с ними. Это как минимум странно, что открытый отряд NT имеет вооружение слегка сильнее, чем засекреченный отряд для зачистки станций от всего живого. Также эскадрон довольно часто начали побеждать, что навевает на мысли о его небольшом баффе.
- Эскадрон смерти теперь спавнится в апокрифических РИГ'ах. Убран рюкзак и стартовый скафандр. Все изменения в `ErtLoadouts.yml`
- Немного баффнута винтовка эскадрона смерти. Теперь она имеет скорострельность 1.8 (было 1.5), 40 урона (было 35), 25 структурного урона (не было вообще). Мне кажется, что данная винтовка должна …
> DeathSquad buff

- Resources/Prototypes/Imperial/ErtCall/ErtLoadouts.yml
- Resources/Prototypes/Imperial/Psychosis/fakeitems.yml
Удалены желтые кислородные баллоны из снаряжения ОБР.
Жёлтые кислородные баллоны были удалены из игры. В связи с этим отряды сломались.
Все кислородные баллоны желтые в снаряжении ОБР заменены на синие. Также fakeitem в психозе заменил.
> Желтые баллоны вырезаны из снаряжения ОБР

- Resources/Prototypes/Imperial/ErtCall/clothing.yml
Исправлено наследование рюкзака эскадрона смерти. Теперь его инвентарь больше.
Он наследовался от обычного рюкзака, что делало его инвентарь очень маленьким для рюкзака эскадрона.
Изменил наследование на рюкзак ОБР. Теперь инвентарь среднего размера и вполне отвечает запросам эскадрона смерти.
> Изменено наследование рюкзаков эксадрона смерти

- Resources/Prototypes/Imperial/Sona/PDA/PDA.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
- Resources/Textures/Imperial/customPDA.rsi/meta.json
Слетел спрайт КПК Sona. Исправил его. Изменил локализацию в тексте задания вора на кражу одеял.
В случае с КПК - ERROR и невозможность проведения ивентов. В случае с целью вора - вводила в заблуждение игроков. Там нужны сугубо одеяла глав.
Добавлен компонент спрайта к КПК Sona. Слово (любое) в задании вора на кражу изменено на (глав)
> Мелкие фиксы апстрима

- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
Добавлен аварийный набор во вторую сумку бригмедика.
При выборе другой сумки, кроме стандартного рюкзака, появляется сумка без аварийного набора.
Добавлен аварийный набор бригмедика в сумку бригмедика.
> Фикс рюкзака БМ'а

- Content.Server/Speech/EntitySystems/StutteringSystem.cs
Добавлен русский язык в регистр заикания
Из-за отсутствия русского регистра не работало заикание в тревожности и в принципе
Добавил новый регистр в StutteringSystem. Комментарий оставлен.
> Фикс тревожности

- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
Фикс сумки бригмедика. Теперь в ней есть аварийный набор
В вещмешке бригмедика не было аварийного набора. 
В прототип заполненного вещмешка бригмедика добавлен аварийный набор. Сторонние файлы не редактировались.
> Фикс вещмешка бригмедика

- Resources/Prototypes/Imperial/Modsuits/Construction/modsuitconstruction.yml
Исправлены размеры неинициализированных РИГ'ов
В старом виде ломали инвентарь при взятии.
Size объектов изменен с численных значений на значения нового инвентаря (и также соответствует размерам сделанных РИГ'ов)
> Исправлены размеры неинициализированных РИГ'ов

- Resources/Textures/Structures/Walls/shuttle.rsi/meta.json
Фикс стен шаттлов, чтобы они не выдавали ERROR при разборке.
Потому что возникает ERROR.
Внес новые стейты в мета файл.
> Небольшой фикс стен шаттлов

- Resources/Prototypes/Imperial/Modsuits/misc.yml
Затраты на одного бойца ядерных оперативников, на котором заточена основная боевая мощь отряда оказалась слишком маленькой, что-бы компенсировать что-то либо ещё в основном закупе
Повышение цены для военного РИГа предназначена для того, что-бы команда  оперативников компенсировала бойца на котором сосредоточена основная боевая мощь отряда чем-то другим в закупе, расходниками, оружием и т.д
Текст писала нейронка
> Повышает цену Тактического рига до 70 тк

- Resources/Prototypes/Imperial/Modsuits/misc.yml
Тактический риг не делает раунд весёлым, а меры, принятые для его дебаффа в https://github.com/imperial-space/space-station14-public/pull/197 не удались. Ничего не изменилось. Можно, конечно, продолжать добавлять по 5 тк каждый ПР, но проблема с тактическим ригом фундаментальна -- ему нужен реворк, а в подобном виде он не должен быть в игре. Через некоторое время отправлю ПР-баланс Тактического рига или вовсе его удалю.
> Временно аннигилирует тактический риг из аплинка

- Content.Client/Administration/UI/AdminMenuWindow.xaml.cs
- Content.Client/Administration/UI/Bwoink/BwoinkWindow.xaml
Изменены размеры окон админов, чтобы при открытии слова не накладывались друг на друга
Неудобно для администрации.
- Изменена ширина у окна администрации с `650` до `700`
- Изменена ширина у окна ахелпа с `900` до `1000`
> Фикс админ размера админ окон, чтобы они нормально открывались

- Resources/Prototypes/Imperial/MiniCrossbow/uplink_catalog.yml
Изменяет стоимость энерго-арбалетика с 11 до 8 ТК
Энерго-арбалетик в настоящее время имеет ограниченные возможности использования в качестве самостоятельного оружия из-за его высокой стоимости, однако снижение цены может сделать его более доступным и популярным среди пользователей. Это также откроет новые возможности для создания уникальных комбинаций и тактических применений. В настоящее время стоимость энерго-арбалетика в 11 ТК не соответствует его функциональным возможностям и потенциалу, и уменьшение цены может сделать его более привлекательным для широкого круга потенциальных пользователей.
> Баланс цены энерго-арбалетика

- Resources/Prototypes/ai_factions.yml
Исправлена фракция дед сквада. Теперь её считают за врага все, кроме НаноТрайзен. 
Потому что все враждебные мобы не атаковали эскадрон.
Фракция эскадрона смерти занесена во враги всех фракций, изначально враждебных к НТ. Также добавил комментарии.
> Исправление фракции дедов

- Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
Исправление бага с фейковыми ядерными оперативниками в манифесте
Видимо, что при окончании раунда вызываются методы OnRoundEndText всех режимов, которые отвечают за записыванние в манифест информации о них. OnRoundEndText в системе нюки не имел заглушку, если самого режима не было, поэтому при любых обстоятельствах появлялось сообщение о ядерах.
> Багфикс фейковых ядеров в манифесте

- Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
Исправлены неправильно выставленные слои в прототипах поисковых навигаторов.
При включении некоторых поисковых навигаторов в консоль выдавалось множество ошибок
Добавил недостающие слои в прототип пинпоинтеров (по сути визарды в будущем сделают также, а конкретнее - 1 мая)
https://github.com/space-wizards/space-station-14/pull/27582
Конфликтов вызвать не должно. Система пинпоинтеров за это время не менялась, а данный твик лишь добавляет слой, убирая достающие ошибки.
> Фикс ошибки из-за потерянного слоя

- Resources/Prototypes/Imperial/DualToySword/dualtoy.yml
Игрушечному лазерному мечу добавлен маленький урон на стамину.
У одинарного меча есть стамина урон. У двойного нет. Не порядок! Сделал минимальный стамина урон, чтобы это не превратилось в очередную стан мету. По итогу человеку без стамина резиста нужно нанести 50 ударов (с учетом скорости дсворда вполне приемлемо). 
Добавлен компонент `StaminaDamageOnHit` к игрушечному лазерному мечу. При желании могу снизить и до 1 стамина дамага, но тогда он будет намного хуже одинарного)
> Стамина урон у дсворда

- Resources/Prototypes/Imperial/ChemistryRework/Reactions/chemReactionsRework.yml
При варке кетопирида масло входящее в его состав становилось пеплом из за новой реакции которую добавили визарды в апстриме
Я понизил температуру для синтеза кетопирида до 510 кельвинов, чтобы реакция происходила раньше, чем масло станет пеплом.
> Багфикс варки кетопирида

- Resources/Prototypes/Imperial/Brigmedic/brigmedic.yml
- Resources/Prototypes/Imperial/Brigmedic/brigmedicIDCard.yml
- Resources/Prototypes/Imperial/Brigmedic/brigmedicgearpreset.yml
- Исправлен аварийный набор бригмедика. Теперь у него нормальный размер. Заменен ребризер на наш кастомный. Наполнение отредактировано.
- Ребризер по стандарту снят с лица бригмедика. Теперь пусть достает из набора
- Исправлено отображение иконки на консоли криминала на паблике
- Добавлен трекер в паблик
В результате переноса в отдельную роль пострадали некоторые предметы из-за разногласий между пабликом и привейтом
Все исправления в соответствующих папках бригмедика. За них не заходил. Отредактированы brigmedic.yml со снаряжением бригмедика, добавлен `- type: PresetIdCard` в карту бригмедика для корректного отображения роли на паблике. В пресет добавлен трекер и убран ребризер по стандарту
> Фикс бригмедика

- Content.Shared/RCD/Systems/RCDSystem.cs
Исправлен баг РСУ, теперь нельзя убрать плитку находясь за стеной
Система Рсу работала в диапазоне одного тайла от игрока, но вот если игрок кликал ровно на один тайл от себя, то это позволяло ему убрать плитку, находящуюся за стеной или другим объектом.
> Багфикс РСУ

- Resources/Prototypes/Catalog/uplink_catalog.yml
Удален ванильный штурмовой борг ЯО.
Есть наша версия киборга, к тому же эта отличается по балансу и по техническим характеристикам
Строчка с возможностью покупки борга в аплинке закомментирована с припиской, что сделано нами. Самого борга не трогал, может для ивентов захотят использовать.
> Удален ванильных борг ЯО из аплинка

- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
В капитанском ящике №3 теперь есть водолазки.
Разработчики добавили в игру третий ящик капитана, в котором свое наполнение (просто без лазера). В нем не было наших штук.
В прототип нового ящика капитана прописана наша одежда и вещи. Комментарии оставлены.
> FixCaptainLocker

- Content.Server/Ghost/Roles/Components/GhostRoleComponent.cs
Гост ролям возвращены описания по умолчанию
После всех обнов почему-то пропала строчка о дефолтных правилах гост ролей
Добавлено ghost-role-component-default-rules в значение правил по умолчанию.
> Фикс отображения правил у гост ролей

- Resources/Prototypes/Imperial/Brigmedic/brigmediclocker.yml
Изменено наполнение ящика бригмедика. Убраны ванильные визардовские предметы. Заменены на наши.
Потому что отсутствовали наши вещи+ванильные были со старыми текстурами
Добавлены новые предметы в прототип ящика бригмедика. Ванильная одежда закомментирована. В сторонние файлы изменения не вносились.
> Фикс наполнения ящика бригмедика

- Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
Исправлен баг с ядерами в манифесте. Теперь в манифесте корректно отображаются их имена и состояние команды на конец раунда. 
Теперь все компоненты антагов хранятся не в MindContainerComponent, а непосредственно в MindComponent, поэтому EntityQueryEnumerator не мог найти сущность с компонентом ядеров.
> Багфикс ядеров в манифесте. Опять.

- Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Небольшой фикс прыжков БСС шаттлов, чтобы они могли прыгать даже с большой массой
Некоторые наши огромные шаттлы не могли в БСС прыжки. 
`FTL limit` для шаттлов поднят с массы в 300 единиц до 600.
> Фикс БСС прыжков

- Resources/Prototypes/Entities/Objects/Misc/tiles.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
Исправлен тайл укрепленной плитки. Поправил локализацию в задании вора на кражу плащей глав
При крафте укрепленной плитки у людей напрочь ломался крафт других предметов. Ну а кривая локализация вводила игроков в заблуждение.
- Добавлен компонент `Construction` к укрепленной плитке, чтобы адекватно работала целевая нода. 
- Изменен перевод в задании вора на корректный с "головной убор" на "плащ главы"
> Маленькие баг фиксы

- Resources/Prototypes/Recipes/Construction/Graphs/machines/computer.yml
Изменено количество выпадающих со сломанного компьютера осколков стекла с 2 на 1.
Служило способом дюпа стекла.
У `ComputerBroken` изменено количество осколков стекла с 2 на 1.
> Фикс дюпа стекла

- Content.Server/Revenant/EntitySystems/RevenantSystem.Abilities.cs
Багфикс способности ревенанта "Overload Lights"
Похоже, что использовались устаревшие методы обнаружения компонентов на сущности или же некоторые компоненты были полностью вырезаны с сущностей.
> Багфикс способности ревенанта "Overload Lights"

- Content.Server/Electrocution/ElectrocutionSystem.cs
- Content.Shared/Prying/Systems/PryingSystem.cs
- Content.Shared/Prying/events/PryingEvent.cs
Фикс фикса с фиксом фикса зомби
Мне показалось, что отменять ивент в Electrocutionsystem - это отличная идея, хотя сама проверка на наличие питания/изолей и т. д. находится дальше. Поэтому DoAfter с открытием двери всегда отменялся. Я просто заменил ивент на обычный, так как при поражении током DoAfter все равно собьется.
> Фикс фикса с фиксом фикса зомби

- Resources/Prototypes/Imperial/Special Officer/SpecialOfficerClothes.yml
- Resources/Prototypes/Imperial/Special Officer/SpecialOfficerSpawner.yml
Исправлены ботинки ОСО, больше они не имеют компонент хранилища, использующийся у подобной обуви до апстрима. Сама сущность ОСО при появлении теперь сразу обладает имплантом МЩ и принадлежит к фракции Эскадрона.
С апстримом были упрощён прототип ботинок с слотом личного оружия: вместо компонента хранилища с вайтлистом теперь используется компонент слота для предмета с аналогичным белым списком. Однако, ботинкам ОСО в своём прототипе зачем-то также присваивался компонент хранилища, несмотря на то, что те уже имели его от парента, в котором тот, соответственно, был заменён на компонент ItemSlots с апстримом. В связи с этим компонент хранилища и был удалён из файла прототипа. 
С целью исправить небольшие косяки в прототипе и облегчить жизнь ГеймМастерам и участникам ивентов, занявшим данную …
> Небольшие изменения Офицера Спецопераций и его снаряжения

- Resources/Prototypes/Imperial/ImperialClothes/ImperialCloak.yml
Фикс бага с плащом ГСБ. Теперь он является целью вора.
Так как формальный плащ ГСБ является нашей разработкой, то и в целях вора он не был прописан. 
Добавил компонент `StealTarget` плащу ГСБ. Теперь ворам будет его засчитывать.
> Плащ ГСБ теперь цель вора

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
В вайтлист ресурсов техфаба патронов добавлены слитки для печати особенных патронов.
Видимо при изменении крафта транквилизаторных патронов забыли, что есть техфаб патронов, в котором также можно их печатать. А у него не было вайтлиста на слитки. Отсюда выходило, что крафт патронов в нем есть, а ресурсы положить для крафта нельзя. Это исправляет данную проблему
Добавлен ресурс `Ingot` в вайтлист техфаба патронов. Теперь он может кушать золотые и серебряные слитки
> Фикс амуниционного техфаба

- Resources/Prototypes/Imperial/CaptainExtraDrip/clothing.yml
- Resources/Prototypes/Imperial/ImperialClothes/ImperialCloak.yml
Теперь торжественный плащ ГСБ, альтернативные плащи капитана из кэпомата воспринимаются как цели вора. 
Наши альтернативные предметы одежды при краже ворами не засчитывались
Добавлен компонент `StealTarget` к белому плащу капитана, к плащу шерифа, к торжественному плащу ГСБ. Ванильные файлы не затронуты.
> Фикс распознавания плащей как цели вора

- Resources/Prototypes/Imperial/Tiles/imperial_floors.yml
На данный момент, диагональные и половинчатые тайлы-решётки невозможно убрать кусачками, хотя полный тайл-решётку таким образом убрать можно. Эта ПРка фиксит этот недочёт.
> Фикс тайлов-решёток

- Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
- Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
Добавлена бонусная блокировка вызова эвака у станции после объявления войны со стороны ЯО.
Так как недавно была удалена коммуникационная консоль синдиката с одного нашего шаттла, встал вопрос о том, не будут ли вызывать на станции эвак очень быстро, не давая ЯО даже шаг сделать на станции. Возможности отзыва эвака у ЯО быть не должно по стандарту, однако увеличить им время блокировки ничто не мешает
- Введен новый параметр `WarEvacBonusBlock`, которому присвоено значение в 10 минут (можно менять в зависимости от нужд)
- В переменную, проверяющую, можно ли вызвать эвак на станции, добавлена переменная. Ранее было: 
`warTime < nukeops.WarNukieArriveDelay`, теперь: `warTime < nukeops.WarNukieArriveDelay + nukeops.WarEvacBonusBlock`
После объявления войны переменной WarTime присваивается …
> NukeEvacBonusBlock

- Resources/Prototypes/Imperial/MiniCrossbow/battery_guns.yml
Был добавлен UseDelay к энерго-арбалету, проще говоря полосочка что указана внизу в медиа.
Ну типо, онли визуал и позволит чуть лучше контролить арбалет.
> Был добавлен UseDelay к арбалету.

- Content.Server/Imperial/ChristmasAntag/BecomeChristmasAntagConditionSystem.cs
- Content.Server/Imperial/ChristmasAntag/ChristmasAntagRuleSystem.cs
- Content.Server/Imperial/ChristmasAntag/ChristmasAntagSystem.cs
- Content.Server/Imperial/ChristmasAntag/Components/CurseGiftComponent.cs
- Content.Server/Imperial/ChristmasAntag/CurseGiftSystem.cs
- Content.Shared/Imperial/ChristmasAntag/Events/TryToFindTargetSpellEvent.cs
- Resources/Prototypes/Imperial/ChristmasAntag/actions.yml
**Changelog**
- Добавлена способность для поиска цели;
- Добавлены исключения при выборе цели: ядерные оперативники в секрете и одинокий ядерный оперативник больше не могут стать целью антагониста;
- Обновлено склонение слов 'минуты' и 'секунды' при отображении оставшегося до превращения времени;
- Обновлены прототипы подарков создаваемых, после превращения в проклятый подарок, а также после выполнения цели;
- Удалены  "бросания" окружающий предметов при использовании способности спавна подарков антагонистом.
> ChristmasAntag: hot-fix, added find target spell
